### ISSUE TITLE
Being able to bypass the round start countdown

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#10]
When you go to the spectator team after having played on red or blue, you can join a team at the start of a new round and give yourself an early start over anyone else. Me and Verctexius attempted to record an example, but could not get this to happen, so it may be either fixed or we didn't do it correctly.

**Comment by JetBoom** [comment]
Why make an issue then?

**Comment by dissident93** [comment]
Because it can lead to the player running towards the ball seconds before anybody else can. I'll attempt to replicate the bug again, as I know it can be done.
