### ISSUE TITLE
Power struggle issues

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#13]
At times, power struggles will continue even after the punching animation is over (GUI keys disappear as well)
* Example: https://youtu.be/TLzrljRzqB8?t=28s

You can also spin around during a power struggle, punching somebody else away with the force of a power struggle without them being involved.
* Example: https://youtu.be/X-3d3JmnbAg

Both of these were working correctly at one point, but were broken by recent Gmod updates.

**Comment by JetBoom** [comment]
The first one is a desync/prediction issue. What I could do is remove the prediction. It would make the bars lag behind by your ping time but the bug wouldn't happen.

Second one is something new I haven't seen.
