### ISSUE TITLE
Cross countering "stack" bug

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#14]
Occasionally, you will “double” cross counter a player with a single punch. It displays “CROSS COUNTER!” once but the sound effect is played twice, and the player is launched a much further distance.

**Comment by JetBoom** [comment]
Any idea how to replicate?

**Comment by dissident93** [comment]
We finally recorded an example: https://www.youtube.com/watch?v=Q5CTFjCbbA0&feature=youtu.be
