### ISSUE TITLE
Score doesn't show in the tab menu correctly when it's above 2048

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#15]
The score does not show correctly on the Tab menu when a player has above 2048 points (only shows the last 3 digits) Kills should also be renamed as Points, to avoid confusing new players.
* Examples: http://cloud-2.steamusercontent.com/ugc/30731396305131222/6C03B0C2829BC758F9878FC461AF3A4192F9DF58/
* http://cloud-4.steamusercontent.com/ugc/30729409109639227/41B33D4889640DF2E1235A41064CA46CCD1CC02A/
* http://cloud-4.steamusercontent.com/ugc/30728136150391262/CEDE8E01D8D9F160E3AC35779404F2EAA96CB115/

**Comment by JetBoom** [comment]
0cb88a824147631d1ce4ec72ce81a86726b5c604
