### ISSUE TITLE
Spectating team issues

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#18]
The spectator clock does not show how much time is left in the game, only how much time has passed in one round, as well as them having an unnecessary HP bar that is always empty. Also, when switching to the Spectator team, the message will only display “[Username] joined”. The spectating team is also limited by how many players are on the Red Rhinos or Blue Bulls (I.E., 4 guys on the Rhinos, only 4 people can join the spectating team)

**Comment by JetBoom** [comment]
"[Username] joined" is fixed in a fretta13 commit.
