### ISSUE TITLE
"Bodywall" issue in areas with a low ceiling

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#20]
Collision boxes are not shrunk/adjusted when a player is charged tackled in a tunnel or area with a low ceiling, completely blocking both teams from passing until the knocked down player gets back up.
* Example: https://youtu.be/Lm70JXdG3Oo
* Example: https://youtu.be/UrKl-VhrODE?t=7s

**Comment by JetBoom** [comment]
Collision boxes aren't shrunk at all when you're tackled / ragdolled.

**Comment by dissident93** [comment]
Should they be? Players from both teams will be stopped and unable to pass through the area when this happens.

**Comment by JetBoom** [comment]
No, that's the same if they were against a wall or on the ground.
