### ISSUE TITLE
"ondropped" are counted as touchdowns?

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#22]
“ondropped” are counted as touchdowns. This happens nearly every game on Soccer, where a player is hit right before he runs in, and the ball is fumbled into the trigger, causing a touchdown. If this is intended, then ignore this.
* Example: https://youtu.be/DCwDag3WkTc

**Comment by JetBoom** [comment]
Always has been intended. What would the behavior be otherwise?

**Comment by dissident93** [comment]
Perhaps alt, which is currently used to ragdoll, could be able to produce a small lateral while on the run? It's basically what happens when you get hit as your crouch jumping with the ball, as it goes forwards a distance.
