### ISSUE TITLE
Being able to crouch jump over a big pole swing

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#23]
You can crouch jump over a Big Pole’s swing, and are able to not get hit with good timing.
* Example: https://youtu.be/dZ35V1Z12Oo

**Comment by JetBoom** [comment]
Not really a bug. You're just jumping over the swipe. If they aimed upwards it would have hit you.

**Comment by dissident93** [comment]
Should the swipe area be more vertical then?
