### ISSUE TITLE
Not being able to tackle somebody head-on with speed ball

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#24]
You can't tackle someone head-on with speed ball, despite the player with the speed ball being faster. Perhaps this is intended?
* Example: https://youtu.be/WUl08FzGHBg

**Comment by JetBoom** [comment]
It is not intended. Will change to skipping power struggle and using pure speed difference vs. charging ball carrier.

**Comment by JetBoom** [comment]
2aed8b81d9a255768b7d759af807a9ecc13e1910
