### ISSUE TITLE
Momentum/collision box problems

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#26]
Players sometimes lose all momentum and completely stop when charging at a player from a certain angle, even though the game should have registered the other player being knocked down. This issue became worse with recent Garry's Mod update, if that changes anything.

*Example: https://youtu.be/E41_ImZ30Bc?t=37s (watch the blue player lose all momentum)

**Comment by JetBoom** [comment]
That's not really a bug. The blue player slowed down from hitting the red player that didn't have the ball. That put them under charging speed (their animation changes). Maybe you are suggesting the speed loss for tackling someone be reduced?

**Comment by dissident93** [comment]
Probably not the best example to use, but it's also happened to me even though nobody else was around the ball carrier. I believe this only happens when hitting a player from the side, and I don't recall this happening before the recent March update. (at least, not that often)

**Comment by JetBoom** [comment]
Should be a little bit better because of df360ec84255a668589305e58995641bf19b693a

Reduced slowdown from hitting other players from 10% to 3%.
