### ISSUE TITLE
Erratic bouncing blitz ball

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#27]
A bouncing blitz ball behaves erratically, with players sometimes catching it or getting burned and thrown back.
* Example https://youtu.be/E41_ImZ30Bc?t=41s (the first player getting burned is what should happen, the second player however should have be able to recover the ball without being thrown back like player one)

**Comment by JetBoom** [comment]
It's not really behaving erratically. If the ball is going over a certain speed then it burns you. The speed may or may not be too low but it's consistent.

**Comment by dissident93** [comment]
I see. Perhaps the numbers can be adjusted? The second player should have been able to recover the ball, don't you agree?

**Comment by JetBoom** [comment]
df360ec84255a668589305e58995641bf19b693a
