### ISSUE TITLE
Players can sometimes have the swimming animation on land

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#34]
Nothing is affected but the animation. It's not universal and doesn't show to everybody at the same time. No idea on the cause either, but I can test further and find out.

Example: https://www.youtube.com/watch?v=BPHZ-0KFL3A

**Comment by BClark09** [comment]
This is occasionally noticed across all gamemodes. I'm unsure if this is a gamemode issue that can be fixed with Player:AnimRestartGesture() because I can't replicate this issue locally.

**Comment by dissident93** [comment]
So it's a Source Engine bug? No worries, as it doesn't effect how the player plays (although can be confusing to new players, I suppose)

**Comment by dissident93** [comment]
Hasn't been seen in about two years, so it's a non issue.
