### ISSUE TITLE
Spectators are able to tackle players

### ISSUE THREAD

**Issue by Verctexius** [JetBoom/extremefootballthrowdown#35]
On both the Official NoXiousNet Extreme Football Throwdown and EFTFL servers, Spectators are able to tackle players from both the Red Rhinos and Blue Bulls. I am not sure if the servers use different versions so I recorded examples on both servers.

Example on NoXiousNet: https://youtu.be/_GZdXvJ_oiY
Example on EFTFL: https://youtu.be/mqPgUns3Ghw

**Comment by dissident93** [comment]
They don't, the server one just lacks the NoXiousNet specific things (menu, shop, emotes, etc)

**Comment by JetBoom** [comment]
3c0208604be94696b2fa2a36e6ecee4740b5d579
