### ISSUE TITLE
Missing UI

### ISSUE THREAD

**Issue by Verctexius** [JetBoom/extremefootballthrowdown#37]
Currently on the EFTFL server, parts of the UI is missing. 

These script errors were from my console:
 [ERROR] gamemodes/extremefootballthrowdown/gamemode/cl_init.lua:1021: attempt to call global 'BetterScreenScale' (a nil value)
  1. DrawMinimap - gamemodes/extremefootballthrowdown/gamemode/cl_init.lua:1021
   2. OnHUDPaint - gamemodes/extremefootballthrowdown/gamemode/cl_init.lua:1126
    3. HUDPaint - gamemodes/fretta13/gamemode/cl_hud.lua:84
     4. unknown - gamemodes/fretta13/gamemode/cl_hud.lua:82

Image of missing UI:
http://cloud-4.steamusercontent.com/ugc/31865560761859001/88D1489F76B8EA635FAA00BE88E7F889A8805D76/

For NoXiousNet, the UI is fine but the mini map had problems with the map Sky Metal. The mini map does not show the entire map, unlike Turbines which did have a full mini map.
Example image: http://cloud-4.steamusercontent.com/ugc/527261519563959075/9885D329870101671F99EE50B68B5BAB9FFE5F8B/

**Comment by JetBoom** [comment]
a5fa45a14e58bdc3b2482662baeecb3c051c52c4
