### ISSUE TITLE
New input method for power struggles

### ISSUE THREAD

**Issue by BClark09** [JetBoom/extremefootballthrowdown#39]
I've been hearing an increasing number of reports, complaints and queries of people using scripts to handle repeatable key presses, this is pretty simple to set up. I'm wondering if it's worth changing the input style to something less repeatable. For instance:
- Same style and set up, but each alternative button is randomly generated to a different key.
- DDR style mini-game (like NoXRP) where the first person to fail loses the struggle?

I'd prefer the first, but just an enhancement suggestion.

**Comment by dissident93** [comment]
Perhaps a combination of the current way and the first suggestion? After 2-3 seconds, the keys would switch.
