### ISSUE TITLE
Able to tackle people with any weapon (including the ball)

### ISSUE THREAD

**Issue by ChiefTuK** [JetBoom/extremefootballthrowdown#50]
You're able to tackle people with any weapon as long as you're going fast enough to tackle. On the public/league server, this mainly happens on maps with jumppads such as Space Jump or Oasis, where when you're carrying a weapon you go through the jumppad. Once you land you start slowing down, and if there is a player infront of you, you'll be able to tackle him.

Video: https://www.youtube.com/watch?v=Tv1eWVPPijE

**Comment by JetBoom** [comment]
Intended.
