### ISSUE TITLE
Server Latency Issues

### ISSUE THREAD

**Issue by ChiefTuK** [JetBoom/extremefootballthrowdown#52]
People behind you will grab the ball, unless you're farther than them at a certain distance. You sometimes phase through the ball when an enemy throws it, instead of catching it. People with the Big Pole can swing at you much further than you can swing at them (Same for with the Beatdown Stick, but a little less noticeable). When other people tackle you, they appear further behind you. But when you tackle others, you have to be phasing through him to tackle you.

**Comment by JetBoom** [comment]
This is just the nature of the engine really so I'm not sure if I'll be able to do anything about it.
