### ISSUE TITLE
Round start spawn camera angle issue

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#8]
Turning the camera as soon as the next round begins will affect which direction you’re facing.
  * Example: https://youtu.be/c5jHyptPbHc?t=10s
  * Example: https://youtu.be/AbonmwgBPVE?t=11s

**Comment by BClark09** [comment]
These should really be separated issues.

**Comment by dissident93** [comment]
Yeah, sorry about that, I've now split them into their own issue pages.

**Comment by JetBoom** [comment]
Not really an issue if I make it so you can freely turn in the pre-round state.

**Comment by dissident93** [comment]
Not at all, in fact that was a often requested feature from other players.

**Comment by JetBoom** [comment]
df360ec84255a668589305e58995641bf19b693a
