### ISSUE TITLE
Players are able to get permanently stuck inside of another player (until death)

### ISSUE THREAD

**Issue by dissident93** [JetBoom/extremefootballthrowdown#9]
Players can get stuck inside of another player on the opposite team who just spawned/teleported at the exact same place. The only way to for either player to escape is to either suicide or be punched to death.

**Comment by JetBoom** [comment]
Hm. Well I can make it so people don't spawn next to enemy players but it would still block if all the spawn spots are taken.

A better solution may be to just make it so knocked down people have no (movement blocking) collisions but that wouldn't that greatly change the game meta?

**Comment by dissident93** [comment]
Would the second solution also fix issue #20? A knocked down player can't do anything until they get back up anyway, so how much could it really effect the game meta?

**Comment by BClark09** [comment]
It opens up a few new issues, you'd need to push anything inside the collision boundary away before the player 'becomes solid' again.

Not spawning near an enemy should work if the limiting distance was a very close. If there are no spawns that would satisfy I would say that's more a fault with the  map than it is the gamemode.

**Comment by BClark09** [comment]
That or spawning gives you two seconds of invulnerability and no collision.

**Comment by dissident93** [comment]
That would probably be best actually, since it would also prevent being hit and/or stuck as soon as they spawned. They could be given a flashing animation, like retro video games used to have as well.
